### ISSUE TITLE
active speech level 

### ISSUE THREAD

**Issue by songtaoshi** [ImperialCollegeLondon/sap-voicebox#3]
Hi, thanks for you're awesome work. I am wondering what is active speech level. Is it an index to  descript the speaker is speaking or not ?

**Comment by voicemike** [comment]
Hi, Active speech level is defined in the ITU-T P.56 standard as the average power of the speech signal during the intervals that speech is present. It is calculated by adding up the square of the speech samples and dividing by the number of samples for which the speaker is speaking. As a by-product of calculating the active speech level, the algorithm estimates the samples for which the speaker is speaking; this is available as the "vad" output of v_activlev().

**Comment by songtaoshi** [comment]
Very explicit! Thanks very much !
