### ISSUE TITLE
About v_melbankm

### ISSUE THREAD

**Issue by liuhongji2000** [ImperialCollegeLondon/sap-voicebox#4]
Thanks for your  work! But I think there is a mistake in v_melbankm. The outputs of this function are not triangular shaped filters.
For example:
plot((0:128)*8000/256,full(v_melbankm(1,256,8000)).')
The shape of the filter is not a triangle obviously. The function of filter is not linear but logarithmic.
Thank you! Looking forward to your reply!

**Comment by voicemike** [comment]
Thanks for your comment: it is not so much an error as a design choice.

The filters in v_melbankm() are triangular in the mel domain which means that if you plot them on a linear frequency scale, they are approximately logarithmic at high frequencies. If you instead use a mel-scaled frequency axis, the filter shape looks triangular as expected:

plot(v_frq2mel((0:128)*8000/256),full(v_melbankm(1,256,8000)).');

If you want the filters to be triangular in the linear frequency domain, you can instead use v_filtbankm() as in:

plot((0:128)*8000/256,full(v_filtbankm(1,256,8000,[],[],'m')).');

The comments in v_melbankm() mention this issue just below the list of input parameters but it could probably have been made clearer. 

In my view, the v_melbankm() version makes more logical sense but the v_filtbankm() version corresponds to Davis & Mermelstein (1980) and is, I think, more commonly used. I suspect that in most practical applications, it makes very little difference which one you use but I don't know of anyone who has investigated this in detail.

Hope this clarifies things. Mike

**Comment by voicemike** [comment]
As a postscript, v_filtbankm(), copes correctly with filters that are too narrow to include any DFT bins whereas v_melbankm() copes badly with this case and gives a fatal error if it applies to all filters. Thus compare these two:

plot((0:128)*8000/256,full(v_melbankm(2,256,8000,0.2,0.204)).')

plot((0:128)\*8000/256,full(v_filtbankm(2,256,8000,0.2\*8000,0.204\*8000,'m')).')

In the v_melbankm version, only one of the filters has any non-zero terms whereas in the v_filtbankm version both filters are well defined. Of course this situation is unlikely in normal use but it is possible at low frequencies if the DFT has low resolution.

**Comment by liuhongji2000** [comment]
Thanks for your reply! I understand it.

In MATLAB toolbox of audio, the function melSpectrogram use filters which are triangular in the linear frequency domain. But it really doesn't make a difference.

Thank you!
